title = "FantasticMao's Blog"
theme = "hugo-coder"

languageCode = "zh-cn"
defaultContentLanguage = "zh-cn"
paginate = 20

publishDir = "docs"
enableRobotsTXT = true
enableEmoji = true

googleAnalytics = "UA-89151446-1"
disqusShortname = "fantasticmao"

[permalinks]
    posts = "/:year/:month/:day/:title/"

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true

[params]
    author = "FantasticMao"
    description = "我，一个 95 年、黑头发、戴眼镜的小伙子。2016 年参加工作，以 Java 谋生，也对 JavaScript、Python、Golang 感兴趣，想要学习网络编程、分布式架构、云原生领域的技术知识。"
    keywords = "FantasticMao,个人博客,程序员,后端,Java"
    info = ""

    avatarurl = "/images/avatar.jpg"
    favicon_32 = "/favicons/favicon-32x32.png"
    favicon_16 = "/favicons/favicon-16x16.png"
    favicon_apple_touch = "/favicons/apple-touch-icon.png"
    since = 2016

    custom_css = ["css/custom.css"]

    icpRecord = "浙ICP备17009730号"

[[params.social]]
    name = "GitHub"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/fantasticmao/"
[[params.social]]
    name = "语雀"
    icon = "iconfont iconfont-yuque"
    weight = 2
    url = "https://www.yuque.com/fantasticmao/tech"
[[params.social]]
    name = "WeChat"
    icon = "fab fa-weixin"
    weight = 3
    url = "images/weixin.png"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 4
    url = "https://twitter.com/fantasticmao/"
[[params.social]]
    name = "Instagram"
    icon = "fab fa-instagram"
    weight = 5
    url = "https://www.instagram.com/wonderfulmao/"
[[params.social]]
    name = "RSS"
    icon = "fas fa-rss"
    weight = 6
    url = "/index.xml"

[[menu.main]]
    name = "首页"
    weight = 1
    url = "/"
[[menu.main]]
    name = "归档"
    weight = 2
    url = "/posts/"
[[menu.main]]
    name = "分类"
    weight = 3
    url = "/categories/"
[[menu.main]]
    name = "标签"
    weight = 4
    url = "/tags/"
[[menu.main]]
    name = "关于"
    weight = 5
    url = "/about/"